#Paths of controller
controller:
  base-path: /miempresa/compras/
  api-get-catalog-products: catalog/product
  api-add-product-shopping-cart: add/product/shopping/cart
  api-get-shopping-cart-by-user: shopping/cart/byUser
  api-delete-product-shopping-cart: delete/product/shopping/cart
  api-update-quantity-product-shopping-cart: update/cart/{idProduct}/{nameProduct}/{productQuantity}
  api-get-list-rest-template-response: get/list/resTemplate

#Paths api external
url-external:
  base-path: https://jsonplaceholder.typicode.com
  api-post: /posts

#Valid headers apis
headers:
  id-user: x-id-usuario

#Swagger Config
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

#Asyn config
async-config:
  core-pool-size: 2
  max-pool-size: 2
  queue-capacity: 100
  thread-name: SaveProductThread
  sleep-time: 8000

#Catalog products
product-catalog:
  product:
    -
      id: 1
      nombre: Leche
      descripcion: Producto lacteo de vaca
      precio: 20.5
    -
      id: 2
      nombre: Pan Bimbo
      descripcion: Pan para sandwich
      precio: 46.2
    -
      id: 3
      nombre: Huevos
      descripcion: Producto de gallina
      precio: 47
    -
      id: 4
      nombre: Azucar
      descripcion: Producto endulzante
      precio: 27
    -
      id:  5
      nombre: Sal
      descripcion: Producto para saborizar
      precio: 26.1
    -
      id:  6
      nombre: Mermelada
      descripcion: Producto de fresa
      precio: 23
    -
      id:  7
      nombre: Cajeta
      descripcion: Producto para hotcake
      precio: 18
    -
      id:  8
      nombre: Aceite
      descripcion: Producto de aceite vegetal
      precio: 49
    -
      id:  9
      nombre: Servilletas
      descripcion: Producto de limpieza
      precio: 25
    -
      id:  10
      nombre: Cafe
      descripcion: Producto soluble
      Cafe soluble precio: 76